export const countryFlags = {
    algérie: { code: 'dz', color: '#006633' },
    argentine: { code: 'ar', color: '#75AADB' },
    australie: { code: 'au', color: '#FFCD00' },
    autriche: { code: 'at', color: '#ED2939' },
    belgique: { code: 'be', color: '#EF3340' },
    brésil: { code: 'br', color: '#FFDC00' },
    canada: { code: 'ca', color: '#FF0000' },
    'cap vert': { code: 'cv', color: '#003893' },
    colombie: { code: 'co', color: '#FCD116' },
    croatie: { code: 'hr', color: '#FF0000' },
    curaçao: { code: 'cw', color: '#002B7F' },
    équateur: { code: 'ec', color: '#FFDD00' },
    égypte: { code: 'eg', color: '#CE1126' },
    angleterre: { code: 'gb-eng', color: '#CE1126' },
    france: { code: 'fr', color: '#002395' },
    allemagne: { code: 'de', color: '#000000' },
    ghana: { code: 'gh', color: '#FCD116' },
    haïti: { code: 'ht', color: '#00209F' },
    iran: { code: 'ir', color: '#239E46' },
    "côte d'ivoire": { code: 'ci', color: '#FF8200' },
    japon: { code: 'jp', color: '#000555' },
    jordanie: { code: 'jo', color: '#CE1126' },
    mexique: { code: 'mx', color: '#006847' },
    maroc: { code: 'ma', color: '#C1272D' },
    'pays bas': { code: 'nl', color: '#FF4F00' },
    'nouvelle-zélande': { code: 'nz', color: '#000000' },
    norvège: { code: 'no', color: '#EF2B2D' },
    panama: { code: 'pa', color: '#005293' },
    paraguay: { code: 'py', color: '#D52B1E' },
    portugal: { code: 'pt', color: '#FF0000' },
    qatar: { code: 'qa', color: '#8D1B3D' },
    'arabie saoudite': { code: 'sa', color: '#006C35' },
    écosse: { code: 'gb-sct', color: '#005EB8' },
    sénégal: { code: 'sn', color: '#00853F' },
    'afrique du sud': { code: 'za', color: '#007749' },
    'corée du sud': { code: 'kr', color: '#CD2E3A' },
    espagne: { code: 'es', color: '#C60B1E' },
    suisse: { code: 'ch', color: '#DA291C' },
    tunisie: { code: 'tn', color: '#E70013' },
    'états unis': { code: 'us', color: '#3C3B6E' },
    uruguay: { code: 'uy', color: '#0081C8' },
    ouzbékistan: { code: 'uz', color: '#0099B5' },
    danemark: { code: 'dk', color: '#C60C30' },
    'états-unis': { code: 'us', color: '#3C3B6E' },
    finlande: { code: 'fi', color: '#002F6C' },
    'grande-bretagne': { code: 'gb', color: '#012169' },
    hongrie: { code: 'hu', color: '#CE1126' },
    italie: { code: 'it', color: '#004B87' },
    lettonie: { code: 'lv', color: '#9E3039' },
    slovaquie: { code: 'sk', color: '#0B4EA2' },
    slovénie: { code: 'si', color: '#8EC641' },
    suède: { code: 'se', color: '#FECC00' },
    tchéquie: { code: 'cz', color: '#D7141A' },
};

export const getCountryData = (name) => {
    if (!name) return { code: 'un', color: '#ccc' }; // Default/Unknown
    const normalized = name.toLowerCase().trim();
    return countryFlags[normalized] || { code: 'un', color: '#ccc' };
};
